//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE___ONLINE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG_CHITIET
    {
        public int MaGioHangChiTiet { get; set; }
        public int MaGioHang { get; set; }
        public int MaSach { get; set; }
        public int SoLuong { get; set; }
    
        public virtual GIOHANG GIOHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
