//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE___ONLINE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOSACH
    {
        public int MASACH { get; set; }
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
