//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE___ONLINE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOIKHACHHANG
    {
        public int MAPH { get; set; }
        public int MAKH { get; set; }
        public string THONGTINPHANHOI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
