//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE___ONLINE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.GIOHANG_CHITIET = new HashSet<GIOHANG_CHITIET>();
            this.KHOSACHes = new HashSet<KHOSACH>();
            this.NHAPHANGs = new HashSet<NHAPHANG>();
        }
    
        public int MASACH { get; set; }
        public int MADANHMUC { get; set; }
        public string MADANHMUC_CHILD { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public string NHAXUATBAN { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<int> SOLUONGTONKHO { get; set; }
        public string MOTACHITIET { get; set; }
        public Nullable<System.DateTime> NGAYTHEMSANPHAM { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<int> MANHACUNGCAP { get; set; }
        public string MOTAFILE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual DANHMUC_CHILD DANHMUC_CHILD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG_CHITIET> GIOHANG_CHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOSACH> KHOSACHes { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAPHANG> NHAPHANGs { get; set; }
        public virtual ANHSACH ANHSACH { get; set; }
        public virtual CHITIETSACH CHITIETSACH { get; set; }
    }
}
