//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE___ONLINE.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBS : DbContext
    {
        public WebBS()
            : base("name=WebBS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<CHUONGTRINHKHUYENMAI> CHUONGTRINHKHUYENMAIs { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
        public virtual DbSet<DANHMUC_CHILD> DANHMUC_CHILD { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<GIOHANG_CHITIET> GIOHANG_CHITIET { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHOSACH> KHOSACHes { get; set; }
        public virtual DbSet<LICHSUMUAHANG> LICHSUMUAHANGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHAPHANG> NHAPHANGs { get; set; }
        public virtual DbSet<PHANHOIKHACHHANG> PHANHOIKHACHHANGs { get; set; }
        public virtual DbSet<PHUONGTHUCTHANHTOAN> PHUONGTHUCTHANHTOANs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TAIKHOAN_ADMIN> TAIKHOAN_ADMIN { get; set; }
        public virtual DbSet<TAIKHOANKHACHHANG> TAIKHOANKHACHHANGs { get; set; }
        public virtual DbSet<USER_ADMIN> USER_ADMIN { get; set; }
        public virtual DbSet<USER_NV> USER_NV { get; set; }
        public virtual DbSet<VOUCHER> VOUCHERs { get; set; }
        public virtual DbSet<VOUCHER_KHACHHANG> VOUCHER_KHACHHANG { get; set; }
        public virtual DbSet<ANHSACH> ANHSACHes { get; set; }
        public virtual DbSet<CHITIETSACH> CHITIETSACHes { get; set; }
    }
}
