CREATE DATABASE WebBanSach
GO
USE WebBanSach
GO
 
--role--
sp_addrole 'ADMIN';
sp_addrole 'NHANVIEN';
sp_addrole 'KHACHHANG';

CREATE TABLE USER_ADMIN(
	MAADMIN INT IDENTITY PRIMARY KEY,
	TENADMIN NVARCHAR(30)
)



CREATE TABLE USER_NV(
	MANV INT IDENTITY PRIMARY KEY,
	TENNHANVIEN NVARCHAR(30)
)


--Tài Khoản Nhân viên--
CREATE TABLE TAIKHOAN (
    MaTK INT IDENTITY PRIMARY KEY,
	MANV INT NOT NULL,
    TenDangNhap NVARCHAR(50) UNIQUE,
    MatKhau NVARCHAR(255),
    VaiTro NVARCHAR(20) DEFAULT  N'Nhân viên'
	CONSTRAINT FK_TAIKHOAN_USERNV FOREIGN KEY (MANV) REFERENCES USER_NV(MANV)
);


--TÀI KHOẢN ADMIN--
CREATE TABLE TAIKHOAN_ADMIN(
	MaTK INT IDENTITY PRIMARY KEY,
	MAADMIN INT NOT NULL,
    TenDangNhap NVARCHAR(50) UNIQUE,
    MatKhau NVARCHAR(255),
    VaiTro NVARCHAR(20) DEFAULT  N'Admin'
	CONSTRAINT FK_TAIKHOAN_USERADMIN FOREIGN KEY (MAADMIN) REFERENCES USER_ADMIN(MAADMIN)
)


--NHÀ CUNG CẤP--
CREATE TABLE NHACUNGCAP(
	MANHACUNGCAP INT IDENTITY(1,1) PRIMARY KEY,
	TENNHACUNGCAP NVARCHAR(150) NULL,
	DIACHI NVARCHAR(250) NULL
)



-- BẢNG DANH MỤC --
CREATE TABLE DANHMUC(
	MADANHMUC INT IDENTITY(1,1) PRIMARY KEY,
	TENDANHMUC NVARCHAR(100)
)
GO


--DANH MỤC CON--
CREATE TABLE DANHMUC_CHILD(
	MADANHMUC INT NOT NULL, 
	MADANHMUC_CHILD NCHAR(30) NOT NULL PRIMARY KEY,
	TENDANHMUC NVARCHAR(100),
	CONSTRAINT FK_DMC_DM FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC)
)
GO

-- BẢNG SÁCH --
CREATE TABLE SACH(
	MASACH INT IDENTITY(1,1) PRIMARY KEY,
	MADANHMUC INT NOT NULL,
	MADANHMUC_CHILD NCHAR(30) NOT NULL,
	TENSACH NVARCHAR(500) NOT NULL,
	TACGIA NVARCHAR(50),
	NHAXUATBAN NVARCHAR(50),
	GIABAN DECIMAL(18,2),
	SOLUONGTONKHO INT,
	MOTACHITIET NVARCHAR(300),
	NGAYTHEMSANPHAM DATETIME DEFAULT GETDATE(),
	NGAYCAPNHAT DATETIME,
	MANHACUNGCAP INT NULL,
	CONSTRAINT FK_SACH_NHACUNGCAP FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP),
	CONSTRAINT FK_SACH_DANHMUC FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC),
	CONSTRAINT FK_SACH_DANHMUCCH FOREIGN KEY (MADANHMUC_CHILD) REFERENCES DANHMUC_CHILD(MADANHMUC_CHILD)
)
GO

SELECT * FROM SACH

--CHI TIẾT SÁCH--

CREATE TABLE CHITIETSACH(
	MASACH INT NOT NULL, 
	NGONGNU NVARCHAR(50),
	KICHTHUOC VARCHAR(30),
	LOAIBIA NVARCHAR(30),
	SOTRANG INT, 
	CONSTRAINT FK_CTS_S FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

)

--BẢNG ẢNH SẢN PHẨM--
CREATE TABLE ANHSACH(
	MASACH INT NOT NULL, --FK
	LINKANH VARCHAR(100),
	CONSTRAINT FK_A_sACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)


--KHO SÁCH--
CREATE TABLE KHOSACH(
	MASACH INT NOT NULL,
	MAKHO NCHAR(10) NOT NULL,
	TENKHO NVARCHAR(100) NULL,
	CONSTRAINT PK_KHOSACH PRIMARY KEY (MASACH, MAKHO),
	CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)

--PHƯƠNG THỨC THANH TOÁN--

CREATE TABLE PHUONGTHUCTHANHTOAN(
	MAPHUONGTHUC INT IDENTITY PRIMARY KEY,
	TENPHUONGTHUC NVARCHAR(200)
)

-- BẢNG ĐƠN HÀNG -- 
CREATE TABLE DONHANG(
    MADONHANG INT IDENTITY(1,1) PRIMARY KEY,
	MANV INT NOT NULL, --MÃ TÀI KHOẢN NHÂN VIÊN/ MÃ NHÂN VIÊN
	MAKH INT NOT NULL,
    NgayDat DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(18,2) NULL,
    DiaChiGiaoHang NVARCHAR(255) NULL,
	TRANGTHAI NVARCHAR(30) DEFAULT N'ACTIVE',
	MAPHUONGPHUC INT NULL,
	CONSTRAINT FK_DONHANG_USERNV FOREIGN KEY (MANV) REFERENCES USER_NV(MANV),
	CONSTRAINT FK_DONHANG_PHUONGTHUCTHANHTOAN FOREIGN KEY (MAPHUONGPHUC) REFERENCES PHUONGTHUCTHANHTOAN(MAPHUONGTHUC)
    
)
--ALTER TABLE DONHANG
--ADD MAPHUONGPHUC INT

--ALTER TABLE DONHANG
--ADD CONSTRAINT FK_DONHANG_PHUONGTHUCTHANHTOAN FOREIGN KEY (MAPHUONGPHUC) REFERENCES PHUONGTHUCTHANHTOAN(MAPHUONGTHUC)

--SELECT * FROM DONHANG


-- BẢNG CHI TIẾT ĐƠN HÀNG --
CREATE TABLE CHITIETDONHANG(
	MACHITIETDONHANG INT IDENTITY(1,1) PRIMARY KEY,
	MADONHANG INT NOT NULL,
	MASACH INT NOT NULL,
	SOLUONG INT,
	GIATAITHOIDIEMMUA DECIMAL(18,2),

	CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG),
	CONSTRAINT FK_CHITIETDONHANG_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)
GO


--KHÁCH HÀNG--
CREATE TABLE KHACHHANG (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh NVARCHAR(10) NULL, -- Nam / Nu
    SDT NVARCHAR(20) NULL,
    Email NVARCHAR(100) NULL,
    DiaChi NVARCHAR(255) NULL,
    CMND_CCCD NVARCHAR(20) NULL,
    LoaiKhachHang NVARCHAR(20) DEFAULT N'ThongThuong', -- ThongThuong / VIP,
    NgayTao DATETIME DEFAULT GETDATE()
)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

--TÀI KHOẢN KHÁCH HÀNG--

CREATE TABLE TAIKHOANKHACHHANG (
    MaTK INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap NVARCHAR(50) UNIQUE NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL,
    VaiTro NVARCHAR(20) NOT NULL,  
    MaKH INT NULL,                  
    CONSTRAINT FK_TAIKHOAN_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
)

--LICH SU MUA HANG--
CREATE TABLE LICHSUMUAHANG(
	MAKH INT NOT NULL,
	MADONHANG INT NOT NULL,
	NGAYTAO DATETIME DEFAULT GETDATE(),
	CONSTRAINT PK_LICHSUMUAHANG PRIMARY KEY(MAKH,MADONHANG),
	CONSTRAINT FK_LICHSUMUAHANG_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_LICHSUMUAHANG_DONHANG FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG)

)

-- Giỏ hàng
CREATE TABLE GIOHANG (
    MaGioHang INT IDENTITY PRIMARY KEY,
    MaKH INT NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    TrangThai NVARCHAR(20) DEFAULT N'Active', -- Active, Ordered
    CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
)

-- Chi tiết giỏ hàng
CREATE TABLE GIOHANG_CHITIET (
    MaGioHangChiTiet INT IDENTITY PRIMARY KEY,
    MaGioHang INT NOT NULL,
    MaSach INT NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT FK_GIOHANGCHITIET_GIOHANG FOREIGN KEY (MaGioHang) REFERENCES GIOHANG(MaGioHang),
    CONSTRAINT FK_GIOHANGCHITIET_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MASACH)
)


CREATE TABLE CHUONGTRINHKHUYENMAI(
	MACT NCHAR(100) NOT NULL PRIMARY KEY,
	TENCT NVARCHAR(100) NOT NULL
)


-- Voucher
CREATE TABLE VOUCHER (
	MACT NCHAR(100) NOT NULL,
    MaVoucher INT IDENTITY PRIMARY KEY,
    TenVoucher NVARCHAR(100) NOT NULL,
    GiamGia DECIMAL(18,2) NOT NULL, -- giá trị giảm,
	SOLUONG INT,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    TrangThai NVARCHAR(20) DEFAULT N'Active' -- Active, Used, Expired,
	CONSTRAINT FK_VOUCHER_CHUONGTRINHKHUYENMAI FOREIGN KEY (MACT) REFERENCES CHUONGTRINHKHUYENMAI(MACT)
)

-- Voucher áp dụng cho khách hàng (nếu muốn)
CREATE TABLE VOUCHER_KHACHHANG (
    MaVoucherKH INT IDENTITY PRIMARY KEY,
    MaVoucher INT NOT NULL,
    MaKH INT NOT NULL,
    CONSTRAINT FK_VOUCHERKH_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher),
    CONSTRAINT FK_VOUCHERKH_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
)

-- Voucher áp dụng cho đơn hàng
ALTER TABLE DONHANG
ADD MaVoucher INT NULL,
CONSTRAINT FK_DONHANG_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher)

--THANH TOÁN--
CREATE TABLE THANHTOAN(
	MADONHANG INT NOT NULL,
	MAKH INT NOT NULL,
	CONSTRAINT PK_THANHTOAN PRIMARY KEY(MADONHANG, MAKH),
	CONSTRAINT FK_THANHTOAN_DONHANG FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG),
	CONSTRAINT FK_THANHTOAN_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)


--PHẢN HỒI--
CREATE TABLE PHANHOIKHACHHANG(
	MAPH INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT NOT NULL,
	THONGTINPHANHOI NVARCHAR(2000),
	CONSTRAINT FK_PHANHOIKHACHHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

--NHẬP HÀNG--
CREATE TABLE NHAPHANG(
	MANHACUNGCAP INT NOT NULL,
	MASACH INT NOT NULL,
	TENSACH NVARCHAR(200),
	SOLUONG INT NOT NULL,
	CONSTRAINT PK_NHAPHANG PRIMARY KEY (MANHACUNGCAP, MASACH),
	CONSTRAINT FK_NHAPHANG_NHACC FOREIGN KEY(MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP),
	CONSTRAINT FK_NHAPHANG_SACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH) 
)
GO

SELECT K.TENKHO, S.MASACH, S.TENSACH, S.SOLUONGTONKHO FROM KHOSACH K, SACH S WHERE K.MASACH = S.MASACH


--THÔNG TIN ADMIN--
INSERT INTO USER_ADMIN 
VALUES
(N'Trần Văn Tín')

--THÔNG TIN NHÂN VIÊN--

INSERT INTO USER_NV
VALUES
(N'Nguyễn Linh Nhi'),
(N'Nguyễn Hoàng Tuấn')

--TÀI KHOẢN ADMIN--

INSERT INTO TAIKHOAN_ADMIN(MAADMIN,TenDangNhap,MatKhau)
VALUES
(1,N'admin1',N'123456')

--TAIKHOAN ADMIN/ NHÂN VIÊN
-- Admin
INSERT INTO TAIKHOAN (MANV,TenDangNhap, MatKhau)
VALUES 
(1,N'nhanvien1', N'123456'),
(2,N'nhanvien2', N'password');

select * from TAIKHOAN
--drop table TAIKHOAN

--KHACHHANG--
INSERT INTO KHACHHANG (HoTen, NgaySinh, GioiTinh, SDT, Email, DiaChi, CMND_CCCD, LoaiKhachHang)
VALUES
(N'Nguyen Van A', '1990-05-12', N'Nam', '0909123456', 'a@gmail.com', N'123 Lê Lợi, TP.HCM', '123456789', N'ThongThuong'),
(N'Tran Thi B', '1995-08-20', N'Nu', '0912345678', 'b@gmail.com', N'90 Nguyễn Huệ, Hà Nội', '987654321', N'VIP'),
(N'Le Van C', '2000-01-15', N'Nam', '0987654321', 'c@gmail.com', N'12 Trần Hưng Đạo, Đà Nẵng', '456789123', N'ThongThuong');

--TAIKHOANKHACHHANG--
INSERT INTO TAIKHOANKHACHHANG (TenDangNhap, MatKhau, VaiTro, MaKH)
VALUES
(N'khachhang1', N'kh123', N'KhachHang', 1),
(N'khachhang2', N'kh456', N'KhachHang', 2),
(N'khachhang3', N'kh789', N'KhachHang', 3);

--NHÀ CUNG CẤP--
INSERT INTO NHACUNGCAP (TENNHACUNGCAP, DIACHI)
VALUES
(N'NXB Kim Đồng', N'55 Quang Trung, Hà Nội'),
(N'NXB Trẻ', N'161B Lý Chính Thắng, TP.HCM'),
(N'NXB Giáo Dục', N'81 Trần Hưng Đạo, Hà Nội');



--DANHMUC--
INSERT INTO DANHMUC (TENDANHMUC)
VALUES
(N'English Books'), --1
(N'Sách tiếng Việt'), --2
(N'Văn phòng phẩm'), --3
(N'Quà lưu niệm'); --4

INSERT INTO DANHMUC_CHILD(MADANHMUC,MADANHMUC_CHILD,TENDANHMUC)
VALUES
(1,'Art',N'Art & Photography'),
(1,'Bio',N'Biographies & Memoirs'),
(2,'TNVN',N'Sách thiếu nhi'),
(2,'KYTHUATVN',N'Sách kỹ năng sống'),
(3,'BOOK',N'Tập vở các loại'),
(3,'Bag',N'Balo học sinh - Cặp học sinh'),
(4,'Sti',N'Sticker - Decal trang trí'),
(4,'PK',N'Phụ Kiện - Vật liệu trang trí');

/*
SELECT DANHMUC.MADANHMUC, DANHMUC.TENDANHMUC, DANHMUC_CHILD.TENDANHMUC
FROM DANHMUC, DANHMUC_CHILD
WHERE DANHMUC_CHILD.MADANHMUC = DANHMUC.MADANHMUC
GROUP BY DANHMUC.MADANHMUC, DANHMUC.TENDANHMUC, DANHMUC_CHILD.TENDANHMUC
*/
--SACH--

/*
	MASACH INT IDENTITY(1,1) PRIMARY KEY,
	MADANHMUC INT NOT NULL,
	MADANHMUC_CHILD NCHAR(30) NOT NULL,
	TENSACH NVARCHAR(100) NOT NULL,
	TACGIA NVARCHAR(50) NOT NULL,
	NHAXUATBAN NVARCHAR(50) NOT NULL,
	GIABAN DECIMAL(18,2) NOT NULL,
	SOLUONGTONKHO INT NOT NULL,
	MOTACHITIET NVARCHAR(300),
	NGAYTHEMSANPHAM DATETIME DEFAULT GETDATE(),
	NGAYCAPNHAT DATETIME,

*/

INSERT INTO SACH 
(MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
	--ENGLISH BOOKS 1
		--ART & PHOTOGRAPHY Art
(1,'Art',N'Open Concept Houses by Francesc Zamora - Architecture / Design in English',N'Francesc Zamora',N'Harper Design',450000.00,10,N'Sách lịch sử nghệ thuật toàn cầu',GETDATE(),NULL),
(1,'Art',N'New Architecture London by Prestel - Art & Design book in English - Sách Ngoại Văn - Bìa Cứng',N'Prestel',N'Prestel',700000.00,8,N'Tuyển tập 100 nghệ sĩ đương đại',GETDATE(),NULL),
(1,'Art',N'The Field Guide to Supergraphics by Sean Adams - Sách Ngoại văn - English Book',N'Author C',N'Thames and Hudson',500000.00,12,N'Hướng dẫn toàn diện về lịch sử nghệ thuật',GETDATE(),NULL),
(1,'Art',N' Prototyping for Architects by Mark Burry - Art',N' Mark Burry',N'Thames and Hudson',380000.00,15,N'Những tác phẩm nghệ thuật & nhiếp ảnh nổi bật',GETDATE(),NULL)
	--Biographies @ Memoires
	-- DANHMUC_CHILD: 'Bio' (Biographies & Memoirs)
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(1,'Bio',N'How To Change Your Mind : The New Science Of Psychedelics',N'Author A',N'Publisher A',200000.00,20,N'Tự truyện của một nhân vật nổi tiếng',GETDATE(),NULL),
(1,'Bio',N'Finding My Virginity: The New Autobiography',N'Author B',N'Publisher B',320000.00,15,N'Sinh hoạt và sự nghiệp các họa sĩ',GETDATE(),NULL),
(1,'Bio',N'Disrupting The Game: From The Bronx To The Top Of Nintendo',N'Author C',N'Publisher C',280000.00,12,N'Tiểu sử phụ nữ thành đạt',GETDATE(),NULL),
(1,'Bio',N'Tolkien And The Great War: The Threshold Of Middle-earth',N'Author D',N'Publisher D',350000.00,18,N'Câu chuyện các doanh nhân nổi tiếng',GETDATE(),NULL)

	--SÁCH VIỆT NAM 2
		--TNVN 
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(2,'TNVN',N'Sách Bí Mật Của Rừng','-',N'Nhà Xuất Bản Dân Trí',200000.00,20,N'Tự truyện của một nhân vật nổi tiếng',GETDATE(),NULL),
(2,'TNVN',N'Sách Chú Gấu Bắc Cực','-',N'Nhà Xuất Bản Phụ Nữ Việt Nam',320000.00,15,N'Sinh hoạt và sự nghiệp các họa sĩ',GETDATE(),NULL),
(2,'TNVN',N'Sách Cùng Phiêu Lưu','-',N'Nhà Xuất Bản Kim Đồng',280000.00,12,N'Tiểu sử phụ nữ thành đạt',GETDATE(),NULL)
	
	--KYTHUATVN
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(2,'KYTHUATVN',N'Sách Năng Lượng','-',N'Nhà Xuất Bản Thế Giới',200000.00,20,N'Tự truyện của một nhân vật nổi tiếng',GETDATE(),NULL),
(2,'KYTHUATVN',N'Sách Năng Lượng','-',N'Nhà Xuất Bản Phụ Nữ Việt Nam',320000.00,15,N'Sinh hoạt và sự nghiệp các họa sĩ',GETDATE(),NULL)

	--VĂN PHÒNG PHẨM 3
		--BOOK
	
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(3,'BOOK',N'Sổ Tay lò xo hình B5 - 150 Trang - Nguyễn Trắc','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'BOOK',N'Lốc 5 quyển vở kẻ ngang 80 trang B5 Campus NB-BGIF80','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'BOOK',N'Sổ Còng Sổ Tay A5 B5 Bìa Nhựa Cứng 120 200 Trang Có Thể Thay Lõi Sổ Ruột Sổ Nhiều Size Deli - Phù Hợp Làm Sổ Kế Hoạch Planner, Nhật Kí, Tập Vở Ghi Chép Bullet Journal - HA560 EN204','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'BOOK',N'Sổ Lò Xo A5/B5 Kẻ Ngang 60 Trang 70gsm - One Piece - Deli - Màu Ngẫu Nhiên','-','-',200000.00,20,'-',GETDATE(),NULL)
	--Bag

INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(3,'Bag',N'Ba lô học sinh MẦM NON cao cấp phong cách dễ thương - BEE GEE HS1267','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'Bag',N'Ba lô học sinh cao cấp phong cách dễ thương - BEE GEE HS1218','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'Bag',N'Ba lô học sinh MẦM NON cao cấp phong cách dễ thương - BEE GEE HS1268','-','-',200000.00,20,'-',GETDATE(),NULL),
(3,'Bag',N'Ba lô học sinh cao cấp phong cách dễ thương - BEE GEE HS1225','-','-',200000.00,20,'-',GETDATE(),NULL)

	--QUÀ LƯU NIỆM 4
		--Sti
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(4,'Sti',N'Sticker MiniScape 3D - Teenage MS-03','-','-',200000.00,20,'-',GETDATE(),NULL),
(4,'Sti',N'Sticker MiniScape 3D - Teenage MS-01','-','-',200000.00,20,'-',GETDATE(),NULL),
(4,'Sti',N'Bộ 30 Sticker MiniScape 3D - Teenage MS-011','-','-',200000.00,20,'-',GETDATE(),NULL),
(4,'Sti',N'Bộ 30 Sticker MiniScape 3D - Teenage MS-08','-','-',200000.00,20,'-',GETDATE(),NULL)
	--PK
INSERT INTO SACH (MADANHMUC, MADANHMUC_CHILD, TENSACH, TACGIA, NHAXUATBAN, GIABAN, SOLUONGTONKHO, MOTACHITIET, NGAYTHEMSANPHAM, NGAYCAPNHAT)
VALUES
(4,'PK',N'( Bịch 30 bóng) Set bóng siêu nhũ + bóng trong kim tuyến) phụ kiện trang trí sinh nhật, tiệc tùng,...','-','-',200000.00,20,'-',GETDATE(),NULL),
(4,'PK',N'Bóng bay trang trí sinh nhật, sự kiện jumbo 24”/70cm','-','-',200000.00,20,'-',GETDATE(),NULL),
(4,'PK',N'( Bịch 30 bóng) Set bóng siêu nhũ + bóng trong kim tuyến) phụ kiện trang trí sinh nhật, tiệc tùng,...','-','-',200000.00,20,'-',GETDATE(),NULL)


--GẮN NHÀ CUNG CẤP CHO SÁCH--
UPDATE SACH SET MANHACUNGCAP = 1 WHERE MASACH BETWEEN 1 AND 10;
UPDATE SACH SET MANHACUNGCAP = 2 WHERE MASACH BETWEEN 11 AND 20;
UPDATE SACH SET MANHACUNGCAP = 3 WHERE MASACH > 20;




ALTER TABLE SACH ADD MOTAFILE NVARCHAR(255)

--SELECT * FROM SACH

CREATE PROCEDURE CAPNHAT_MOTAFILE_THEO_MASACH
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE SACH
    SET MOTAFILE = '/Content/Mota/' + CAST(MASACH AS VARCHAR) + '.txt'
    WHERE MOTAFILE IS NULL OR MOTAFILE IS NOT NULL OR MOTAFILE = '';
END;
GO

CREATE PROCEDURE UPDATE_LINKANHTHEOMASACH
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE ANHSACH
	SET LINKANH = '/Content/i'+ CAST(MASACH AS VARCHAR) + '.jpg'
	WHERE LINKANH IS NOT NULL OR LINKANH IS NULL OR LINKANH = '';
END;
GO

--DROP PROC UPDATE_LINKANHTHEOMASACH
--DROP PROC CAPNHAT_MOTAFILE_THEO_MASACH

EXEC CAPNHAT_MOTAFILE_THEO_MASACH
EXEC UPDATE_LINKANHTHEOMASACH


/*
MASACH INT NOT NULL, 
	NGONGNU NVARCHAR(50),
	KICHTHUOC VARCHAR(30),
	LOAIBIA NVARCHAR(30),
	SOTRANG INT
*/
--CHI TIẾT SẢN PHẨM
INSERT INTO CHITIETSACH(MASACH,NGONGNU, KICHTHUOC, LOAIBIA, SOTRANG)
VALUES
(1,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(2,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(3,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(4,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(5,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(6,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(7,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(8,N'Tiếng Anh','15 x 20',N'Bình thường',0),
(9,N'Tiếng Việt','15 x 20',N'Bình thường',0),
(10,N'Tiếng Việt','15 x 20',N'Bình thường',0),
(11,N'Tiếng Việt','15 x 20',N'Bình thường',0),
(12,N'Tiếng Việt','15 x 20',N'Bình thường',0),
(13,N'Tiếng Việt','15 x 20',N'Bình thường',0),
(14,null,'15 x 20 x 30','-','-'),
(15,null,'15 x 20 x 30','-','-'),
(16,null,'15 x 20 x 30','-','-'),
(17,null,'15 x 20 x 30','-','-'),
(18,null,'15 x 20 x 30','-','-'),
(19,null,'15 x 20 x 30','-','-'),
(20,null,'15 x 20 x 30','-','-'),
(21,null,'15 x 20 x 30','-','-'),
(22,null,'20 x 30','-','-'),
(23,null,'20 x 30','-','-'),
(24,null,'20 x 30','-','-'),
(25,null,'20 x 30','-','-'),
(26,null,'20 x 30','-','-'),
(27,null,'20 x 30','-','-'),
(28,null,'20 x 30','-','-')
--ẢNH SẢN PHẨM--

CREATE PROCEDURE ThemAnhSanPhamTuSach
AS
BEGIN
    SET NOCOUNT ON;

    -- Chèn ảnh cho các sách mà chưa có ảnh trong ANHSACH
    INSERT INTO ANHSACH (MASACH, LINKANH)
    SELECT s.MASACH,  'i' + CAST(s.MASACH AS VARCHAR) + '.jpg' 
    FROM SACH s
    WHERE NOT EXISTS (
        SELECT 1 
        FROM ANHSACH a
        WHERE a.MASACH = s.MASACH
    );
END
GO


--drop proc ThemAnhSanPhamTuSach
EXEC ThemAnhSanPhamTuSach
select * from ANHSACH


SELECT *
FROM SACH s, CHITIETSACH cts, ANHSACH a
WHERE s.MASACH = cts.MASACH and s.MASACH = a.MASACH

--KHO SÁCH--
INSERT INTO KHOSACH (MASACH, MAKHO, TENKHO)
SELECT MASACH, 'KHO1', N'Kho Tổng'
FROM SACH;




INSERT INTO PHUONGTHUCTHANHTOAN
VALUES
(N'Thanh toán chuyển khoản ngân hàng'),
(N'Thanh toán bằng momo'),
(N'Thanh toán bằng ship cod')

--DONHANG--
INSERT INTO DONHANG (MANV, MaKH, NgayDat, TongTien, MAPHUONGPHUC, DiaChiGiaoHang)
VALUES
(1,1, GETDATE(), 239000, 1, N'123 Lê Lợi, TP.HCM'),
(1,2, GETDATE(), 150000, 2, N'90 Nguyễn Huệ, Hà Nội'),
(2,3, GETDATE(), 249000, 3, N'12 Trần Hưng Đạo, Đà Nẵng');


SELECT * FROM DONHANG DH , PHUONGTHUCTHANHTOAN PT WHERE DH.MAPHUONGPHUC = PT.MAPHUONGTHUC

--CHITEITDONHANG--
-- Đơn hàng 1
INSERT INTO CHITIETDONHANG (MADONHANG, MASACH, SOLUONG, GIATAITHOIDIEMMUA)
VALUES
(1, 1, 1, 89000),
(1, 3, 1, 150000);

-- Đơn hàng 2
INSERT INTO CHITIETDONHANG (MADONHANG, MASACH, SOLUONG, GIATAITHOIDIEMMUA)
VALUES
(2, 3, 1, 150000);

-- Đơn hàng 3
INSERT INTO CHITIETDONHANG (MADONHANG, MASACH, SOLUONG, GIATAITHOIDIEMMUA)
VALUES
(3, 5, 1, 160000),
(3, 1, 1, 89000);

--SELECT * FROM CHITIETDONHANG CTDH, SACH S, DONHANG DH WHERE CTDH.MASACH = S.MASACH AND CTDH.MADONHANG = DH.MADONHANG



--CHƯƠNG TRÌNH KHUYẾN MÃI

INSERT INTO CHUONGTRINHKHUYENMAI (MACT, TENCT)
VALUES
(N'CT2025', N'Khuyến mãi cuối năm 2025'),
(N'CTVIP', N'Chương trình khách hàng VIP');



--VOUCHER--
INSERT INTO VOUCHER (MACT, TenVoucher, GiamGia, SOLUONG, NgayBatDau, NgayKetThuc, TrangThai)
VALUES
(N'CT2025', N'GIAM10', 10000, 100, '2025-11-01', '2025-12-01', N'Active'),
(N'CT2025', N'GIAM20', 20000, 50,  '2025-11-10', '2025-12-31', N'Active'),
(N'CTVIP',  N'VIP50',  50000, 20,  '2025-11-01', '2025-12-31', N'Active');


-- Voucher áp dụng cho khách hàng
INSERT INTO VOUCHER_KHACHHANG (MaVoucher, MaKH)
VALUES
(1, 1),  -- voucher GIAM10 cho khách hàng 1
(2, 2),  -- voucher GIAM20 cho khách hàng 2
(3, 2);  -- voucher VIP50 cũng cho khách hàng 2\


-- GIỎ HÀNG
-- =======================
INSERT INTO GIOHANG (MaKH, NgayTao, TrangThai)
VALUES
(1, GETDATE(), N'Active'),  -- giỏ hàng của khách 1
(2, GETDATE(), N'Active'),  -- giỏ hàng của khách 2
(3, GETDATE(), N'Active');  -- giỏ hàng của khách 3

-- CHI TIẾT GIỎ HÀNG
-- =======================
-- Giả sử MaGioHang tự động IDENTITY lần lượt là 1,2,3
INSERT INTO GIOHANG_CHITIET (MaGioHang, MaSach, SoLuong)
VALUES
(1, 1, 1),  -- khách 1 mua 1 cuốn "Nhà Giả Kim"
(1, 5, 2),  -- khách 1 mua 2 cuốn "Giáo Trình C++ Cơ Bản"
(2, 3, 1),  -- khách 2 mua 1 cuốn "Ông Già Và Biển Cả"
(2, 7, 1),  -- khách 2 mua 1 cuốn "Đắc Nhân Tâm"
(3, 2, 1),  -- khách 3 mua 1 cuốn "Không Gia Đình"
(3, 12, 1); -- khách 3 mua 1 cuốn "Thiết Kế Cơ Sở Dữ Liệu"

--LỊCH SỬ MUA HÀNG--
INSERT INTO LICHSUMUAHANG (MAKH, MADONHANG)
VALUES
(1,1),
(2,2),
(3,3);

--THANH TOÁN--
INSERT INTO THANHTOAN (MADONHANG, MAKH)
VALUES
(1,1),
(2,2),
(3,3);


--PHẢN HỒI KHÁCH HÀNG--
INSERT INTO PHANHOIKHACHHANG (MAKH, THONGTINPHANHOI)
VALUES
(1, N'Sách rất đẹp, giao hàng nhanh'),
(2, N'Nhân viên tư vấn nhiệt tình'),
(3, N'Sẽ quay lại mua lần sau');





--------------------------------------------------------------PROCEDURE
		--PHÂN QUYỀN--
CREATE PROCEDURE SP_PHANQUYEN @Tendangnhap nchar(50)
AS
	BEGIN
		DECLARE @VAITRO NVARCHAR(20);
		DECLARE @LOGINNAME NVARCHAR(50);
		DECLARE @USERNAME NVARCHAR(50);

		--LẤY VAI TRÒ--
		SELECT @VAITRO = VAITRO
		FROM TAIKHOAN
		WHERE TenDangNhap = @Tendangnhap;

		IF @VAITRO IS NULL
		BEGIN
			PRINT N'TÊN ĐĂNG NHẬP KHÔNG TỒN TẠI TRONG TAIKHOAN';
			RETURN;
		END

		SET @LOGINNAME = @Tendangnhap + '_login';
		SET @USERNAME = @Tendangnhap;

		-- TẠO LOGIN NẾU CHƯA CÓ
    ------------------------------------------------
		IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = @LoginName)
		BEGIN
			EXEC sp_addlogin @LoginName, '123';
		END

		------------------------------------------------
		-- TẠO USER NẾU CHƯA CÓ
		------------------------------------------------
		IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = @UserName)
		BEGIN
			EXEC sp_adduser @LoginName, @UserName;
		END

		-- THÊM ROLE TƯƠNG ỨNG
    ------------------------------------------------
		IF @VaiTro = 'Admin'
			EXEC sp_addrolemember 'ADMIN', @UserName;

		ELSE IF @VaiTro = 'NhanVien'
			EXEC sp_addrolemember 'NHANVIEN', @UserName;

		ELSE IF @VaiTro = 'KhachHang'
			EXEC sp_addrolemember 'KHACHHANG', @UserName;
		END
GO


	--CẤP QUYỀN CHO ADMIN--

CREATE PROCEDURE SP_CapQuyen_ADMIN
AS
BEGIN
    -- Cấp quyền thao tác tất cả bảng
    GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO ADMIN;

    -- Cấp quyền chạy toàn bộ stored procedure
    GRANT EXECUTE ON SCHEMA::dbo TO ADMIN;

    PRINT 'Cấp quyền ADMIN thành công!';
END
GO
	
	--CẤP QUYỀN CHO NHÂN VIÊN--
CREATE PROCEDURE SP_CapQuyen_NHANVIEN
AS
BEGIN
	 PRINT N'Đang cấp quyền cho role NHANVIEN…';

    -- QUYỀN XEM DỮ LIỆU
    GRANT SELECT ON DANHMUC TO NHANVIEN;
    GRANT SELECT ON SACH TO NHANVIEN;
    GRANT SELECT ON KHACHHANG TO NHANVIEN;
    GRANT SELECT ON DONHANG TO NHANVIEN;
    GRANT SELECT ON CHITIETDONHANG TO NHANVIEN;

    -- QUYỀN THÊM (INSERT)
    GRANT INSERT ON DONHANG TO NHANVIEN;
    GRANT INSERT ON CHITIETDONHANG TO NHANVIEN;

    -- QUYỀN CẬP NHẬT (UPDATE)
    GRANT UPDATE ON SACH(SOLUONGTONKHO) TO NHANVIEN;   -- Chỉ được sửa tồn kho
    GRANT UPDATE ON DONHANG TO NHANVIEN;               -- Cập nhật địa chỉ giao hàng, PTTT

    -- KHÔNG CHO PHÉP DELETE
    DENY DELETE ON DANHMUC TO NHANVIEN;
    DENY DELETE ON SACH TO NHANVIEN;
    DENY DELETE ON KHACHHANG TO NHANVIEN;
    DENY DELETE ON DONHANG TO NHANVIEN;
    DENY DELETE ON CHITIETDONHANG TO NHANVIEN;

    PRINT N'Đã cấp quyền thành công cho role NHANVIEN.';
END
GO

	--ĐĂNG NHẬP--
	CREATE PROCEDURE SP_DangNhap
    @TenDangNhap NVARCHAR(50),
    @MatKhau NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. KIỂM TRA ADMIN / NHÂN VIÊN
    IF EXISTS (
        SELECT 1 FROM TAIKHOAN
        WHERE TenDangNhap = @TenDangNhap AND MatKhau = @MatKhau
    )
    BEGIN
        SELECT 
            TenDangNhap,
            VaiTro,
            ThongBao = N'Đăng nhập thành công (ADMIN / NHÂN VIÊN)'
        FROM TAIKHOAN
        WHERE TenDangNhap = @TenDangNhap;

        RETURN;
    END

    -- 2. KIỂM TRA KHÁCH HÀNG
    IF EXISTS (
        SELECT 1 FROM TAIKHOANKHACHHANG
        WHERE TenDangNhap = @TenDangNhap AND MatKhau = @MatKhau
    )
    BEGIN
        SELECT 
            tk.TenDangNhap,
            tk.VaiTro,
            kh.HoTen,
            ThongBao = N'Đăng nhập thành công (KHÁCH HÀNG)'
        FROM TAIKHOANKHACHHANG tk
        LEFT JOIN KHACHHANG kh ON tk.MaKH = kh.MaKH
        WHERE tk.TenDangNhap = @TenDangNhap;

        RETURN;
    END

    -- 3. SAI THÔNG TIN
    SELECT N'SAI TÊN ĐĂNG NHẬP HOẶC MẬT KHẨU' AS ThongBao;
END
GO


CREATE PROCEDURE XOASACH
    @MASACH INT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Xóa tất cả chi tiết đơn hàng liên quan đến sản phẩm
        DELETE FROM CHITIETDONHANG
        WHERE MASACH = @MASACH;

        -- 2. Xóa tất cả chi tiết sách liên quan (nếu có bảng CHITIETSACH)
        DELETE FROM CHITIETSACH
        WHERE MASACH = @MASACH;

        -- 3. Xóa sản phẩm chính
        DELETE FROM SACH
        WHERE MASACH = @MASACH;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000), 
                @ErrorSeverity INT, 
                @ErrorState INT;

        SELECT 
            @ErrorMessage = ERROR_MESSAGE(),
            @ErrorSeverity = ERROR_SEVERITY(),
            @ErrorState = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
GO



	--ĐĂNG KÝ--
CREATE PROCEDURE SP_DangKy
    @HoTen NVARCHAR(100),
    @NgaySinh DATE,
    @GioiTinh NVARCHAR(10),
    @SDT NVARCHAR(20),
    @Email NVARCHAR(100),
    @DiaChi NVARCHAR(255),
    @CMND_CCCD NVARCHAR(20),
    @TenDangNhap NVARCHAR(50),
    @MatKhau NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    -- KIỂM TRA TÊN ĐĂNG NHẬP TRÙNG
    IF EXISTS (SELECT 1 FROM TAIKHOANKHACHHANG WHERE TenDangNhap = @TenDangNhap)
    BEGIN
        SELECT N'Tài khoản đã tồn tại, vui lòng chọn tên khác!' AS ThongBao;
        RETURN;
    END

    -- 1. TẠO KHÁCH HÀNG
    INSERT INTO KHACHHANG (HoTen, NgaySinh, GioiTinh, SDT, Email, DiaChi, CMND_CCCD)
    VALUES (@HoTen, @NgaySinh, @GioiTinh, @SDT, @Email, @DiaChi, @CMND_CCCD);

    DECLARE @MaKH INT = SCOPE_IDENTITY();

    -- 2. TẠO TÀI KHOẢN KHÁCH HÀNG
    INSERT INTO TAIKHOANKHACHHANG (TenDangNhap, MatKhau, VaiTro, MaKH)
    VALUES (@TenDangNhap, @MatKhau, N'KhachHang', @MaKH);

    SELECT N'Đăng ký thành công!' AS ThongBao, @MaKH AS MaKhachHang;
END
GO


SELECT DH.MADONHANG, DH.NgayDat, DH.TongTien,DH.DiaChiGiaoHang,DH.TRANGTHAI, PT.TENPHUONGTHUC, CT.SOLUONG,S.TENSACH, S.GIABAN FROM DONHANG DH, CHITIETDONHANG CT, SACH S, PHUONGTHUCTHANHTOAN PT
WHERE DH.MADONHANG =  CT.MADONHANG AND CT.MASACH = S.MASACH AND DH.MAPHUONGPHUC = PT.MAPHUONGTHUC AND MAKH = 1

SELECT * FROM DONHANG DH, CHITIETDONHANG CT, SACH S, PHUONGTHUCTHANHTOAN PT
WHERE DH.MADONHANG =  CT.MADONHANG AND CT.MASACH = S.MASACH AND DH.MAPHUONGPHUC = PT.MAPHUONGTHUC AND MAKH = 1

SELECT * FROM USER_ADMIN;
SELECT * FROM USER_NV;
SELECT * FROM TAIKHOAN;
SELECT * FROM TAIKHOAN_ADMIN;
SELECT * FROM NHACUNGCAP;
SELECT * FROM DANHMUC;
SELECT * FROM DANHMUC_CHILD;
SELECT * FROM SACH;
SELECT * FROM CHITIETSACH;
SELECT * FROM ANHSACH;
SELECT * FROM KHOSACH;
SELECT * FROM KHACHHANG;
SELECT * FROM TAIKHOANKHACHHANG;
SELECT * FROM GIOHANG;
SELECT * FROM GIOHANG_CHITIET;
SELECT * FROM PHUONGTHUCTHANHTOAN;
SELECT * FROM DONHANG;
SELECT * FROM CHITIETDONHANG;
SELECT * FROM LICHSUMUAHANG;
SELECT * FROM THANHTOAN;
SELECT * FROM PHANHOIKHACHHANG;
SELECT * FROM CHUONGTRINHKHUYENMAI;
SELECT * FROM VOUCHER;
SELECT * FROM VOUCHER_KHACHHANG;


----1----
DROP TABLE GIOHANG_CHITIET;
DROP TABLE CHITIETDONHANG;
DROP TABLE CHITIETSACH;
DROP TABLE ANHSACH;
DROP TABLE KHOSACH;
DROP TABLE VOUCHER_KHACHHANG;
DROP TABLE LICHSUMUAHANG;
DROP TABLE THANHTOAN;
DROP TABLE PHANHOIKHACHHANG;



--2---
DROP TABLE GIOHANG;
DROP TABLE DONHANG;
DROP TABLE VOUCHER;


--3--
DROP TABLE SACH;
DROP TABLE PHUONGTHUCTHANHTOAN;
DROP TABLE NHACUNGCAP;



--4--
DROP TABLE DANHMUC_CHILD;
DROP TABLE DANHMUC;


--5--
DROP TABLE TAIKHOANKHACHHANG;
DROP TABLE TAIKHOAN;
DROP TABLE TAIKHOAN_ADMIN;



--6--
DROP TABLE USER_NV;
DROP TABLE USER_ADMIN;
DROP TABLE KHACHHANG;

--7--
DROP TABLE CHUONGTRINHKHUYENMAI;
